### PR TITLE
fix: Incorrect branch and PR hyperlink for gitlab ci extension

### LINKED ISSUE #260: Gitlab - branch hyperlink
It seems that the branch hyperlink is taking me to a 404 on gitlab, the url is missing:  `/-/tree/`
Correct url:
`https://<gitlab-domain>/<namespace>/<project-name>/-/tree/<branch-name>`

What it links to which results in a 404:
`https://<gitlab-domain>/<namespace>/<project-name><branch-name>`

Here is my testbeats.config.json:
```
{
    "targets": [
      {
        "name": "teams",
        "inputs": {
          "url": "{MS_TEAMS_WEBHOOK_URL}",
          "title": "Playwright Automation - E2E Tests",
          "publish": "test-summary"
        }
      }
    ],
    "extensions": [
      {
        "name": "quick-chart-test-summary"
      },
      {
        "name": "ci-info",
        "inputs": {
          "show_repository": true,
          "show_repository_branch": true,
          "show_build": true,
          "data": [
            {
              "key": "Download Report",
              "value": "{CI_PROJECT_URL}/-/jobs/{CI_JOB_ID}/artifacts/download",
              "type": "hyperlink"
            }
          ]
        }
      }
    ],
    "results": [
      {
        "type": "junit",
        "files": ["results.xml"]
      }
    ]
  }
```

Here is the result:
Screenshot 2024-12-10 201850

Anyway to remove the hyperlink and only have the branch name as a workaround if this is indeed a bug?

### PR DESCRIPTION
**Pull request by leelaprasadv**
**Summary**
- Fixes #260 
- Handle both PR and Branch URL issues in GitLab
- Refactor `src/helpers/ci.js` to into individual ci modules for extensibility
- Add tests for GitLab CI using ci-info extension

### CODE REVIEW

File: src/extensions/extensions.d.ts [hunk 1]
```diff
@@ -5,8 +5,16 @@ export type ICIInfo = {
   repository_name: string
   repository_ref: string
   repository_commit_sha: string
+  branch_url: string
+  branch_name: string
+  pull_request: IPRInfo | boolean
```
Comment (ASaiAnudeep) [inline src/extensions/extensions.d.ts:10]: given the format of other properties, can we update the `pull_request` to `pull_request_name` and `pull_request_url`

Comment (leelaprasadv) [reply src/extensions/extensions.d.ts:10]: I had considered that as one of the option, the problem is with the way we have to determine if there is a PR for gitlab and others. However this felt like a better way to handle without many if conditions.

Let me revisit the changes and see if the logic can be simplified to accommodate the suggestion.

Comment (leelaprasadv) [reply src/extensions/extensions.d.ts]: @ASaiAnudeep Done

**Review by ASaiAnudeep — APPROVED** [review]
